# Generated by Django 4.2.16 on 2024-09-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='UserDetails',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='Password',
            new_name='password',
        ),
    ]
